### ISSUE TITLE
bash:: command not found

### ISSUE THREAD

**Issue by oguzhannkayaa** [debezium/debezium.github.io#826]
I created a docker-compose file and run it. It works fine but when I get inside the containers no command works. even apt-get or apt, it gives only command not found error. I dont know why?

in mac os intel.
docker version: 20.10.13
```
version: '2'
services:
  zookeeper:
    image: debezium/zookeeper
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
  kafka:
    image: debezium/kafka
    ports:
      - 9092:9092
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
  postgres:
    container_name: postgresql
    image: debezium/postgres:11
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=debezium
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
  connect:
    image: debezium/connect
    ports:
      - 8083:8083
      - 5005:5005
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_source_connect_statuses
 ```
```
CONTAINER ID   IMAGE                  COMMAND                  CREATED          STATUS         PORTS                                                                    NAMES
a34e34516bdf   debezium/kafka         "/docker-entrypoint.…"   9 minutes ago    Up 8 minutes   0.0.0.0:9092->9092/tcp                                                   docker-kafka-1
1500945fd17c   debezium/connect       "/docker-entrypoint.…"   21 minutes ago   Up 8 minutes   0.0.0.0:5005->5005/tcp, 0.0.0.0:8083->8083/tcp, 9092/tcp                 docker-connect-1
d475c9993513   debezium/zookeeper     "/docker-entrypoint.…"   21 minutes ago   Up 8 minutes   0.0.0.0:2181->2181/tcp, 0.0.0.0:2888->2888/tcp, 0.0.0.0:3888->3888/tcp   docker-zookeeper-1
58896bc0547b   debezium/postgres:11   "docker-entrypoint.s…"   4 hours ago      Up 8 minutes   0.0.0.0:5432->5432/tcp                                                   postgresql
```
